site_name: rosplat
site_url: https://rosplat.github.io/rosplat-docs/
theme:
  name: material
  icon:
    admonition:
      success: material/key-chain-variant
  font:
    text: false
  features:
    - content.code.select
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra_css:
  - stylesheets/extra.css
 


