site_name: rosplat
site_url: https://rosplat.github.io/rosplat-docs/
theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.blocks.admonition 
  - pymdownx.details
  - pymdownx.superfences

 


